AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create VPC Endpoints"

Parameters:
  EnvironmentType:
    Type: String

  VpcID:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  PrivateSubnet3:
    Type: String

  PrivateRouteTable:
    Type: String

  VPCEnpointSecurityGroup:
    Type: String


Conditions:
  isProdEnvironmentType: !Equals [!Ref EnvironmentType, prod]


Resources:
  MonitoringEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.monitoring"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !If [isProdEnvironmentType, !Ref PrivateSubnet3, !Ref AWS::NoValue]
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  ECRApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.api"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !If [isProdEnvironmentType, !Ref PrivateSubnet3, !Ref AWS::NoValue]
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  ECRDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.ecr.dkr"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !If [isProdEnvironmentType, !Ref PrivateSubnet3, !Ref AWS::NoValue]
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VPCEnpointSecurityGroup
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.logs"
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !If [isProdEnvironmentType, !Ref PrivateSubnet3, !Ref AWS::NoValue]
      VpcEndpointType: 'Interface'
      VpcId: !Ref VpcID

  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: false
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      RouteTableIds: 
        - !Ref PrivateRouteTable
      VpcEndpointType: 'Gateway'
      VpcId: !Ref VpcID