AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation root template | Nested Stacks"

# Parameter definition
Parameters:
  EnvironmentType:
    Description: "Select environment type: Productive or Non-Productive"
    Type: String
    AllowedValues:
      - prod
      - nonprod

  EnvironmentName:
    Description: "Insert environment name. Example: dev"
    Type: String

  PrivateDomainName:
    Description: "Insert domain name. Example: kloudpepper.com"
    Type: String

  VpcCIDR:
    Description: "Insert VPC CIDR"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  PublicSubnet1CIDR:
    Description: "Insert public subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  PublicSubnet2CIDR:
    Description: "Insert public subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  PrivateSubnet1CIDR:
    Description: "Insert private subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  PrivateSubnet2CIDR:
    Description: "Insert private subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  DBPrivateSubnet1CIDR:
    Description: "Insert DB private subnet CIDR of zone A"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  DBPrivateSubnet2CIDR:
    Description: "Insert DB private subnet CIDR of zone B"
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Please insert a valid range

  CreateTransitGateway:
    Description: "Do you want create a new Transit Gateway?"
    Type: String
    Default: TRUE
    AllowedValues:
      - TRUE
      - FALSE

  OtherTransitGatewayID:
    Description: "Optional. Insert Transit Gateway ID. Leave this blank if you are not going to use another Transit Gateway"
    Type: String

  CreateALBCertificate:
    Description: "Do you want to create private certificate authority (CA)?"
    Type: String
    Default: TRUE
    AllowedValues:
      - TRUE
      - FALSE

  OtherARNCertificate:
    Description: "Optional. Insert Certificate ARN. Leave this blank if you are not going to use another certificate stored in ACM"
    Type: String
    Default: ""

  CreateNewAuroraDB:
    Description: "Do you want to create a new database?"
    Type: String
    Default: TRUE
    AllowedValues:
      - TRUE
      - FALSE

  DBSnapshotARN:
    Description: "Optional. DB Snapshot ID to restore database. Leave blank if you are not restoring from a snapshot"
    Type: String
    Default: ""

  DBUser:
    NoEcho: false
    Description: "Insert the username that is used to connect to the database"
    Type: String

  DBPassword:
    NoEcho: true
    Description: "Insert the password that is used to connect to the database"
    Type: String

  CreatePrivateDomain:
    Description: "Do you want to create a private hosted zone?"
    Type: String
    Default: TRUE
    AllowedValues:
      - TRUE
      - FALSE

  OtherHostedZoneIdRoute53:
    Description: "Optional. Insert Hosted Zone ID. Leave this blank if you are not going to use a created private hosted zone"
    Type: String
    Default: ""

  DesiredCount:
    Description: "Insert the number of desired tasks to be executed in each service"
    Type: Number
    Default: 1

  ImageUrlApp1:
    Description: "Insert the url of the App1 container image"
    Type: String
  
  ImageUrlApp2:
    Description: "Insert the url of the App2 container image"
    Type: String


Mappings: 
  Aurora:
    InstanceTypes:
      prod: "db.t2.medium"    # 2 vCPUs + 4 GB
      nonprod: "db.t2.small"  # 1 vCPUs + 2 GB


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: "ENVIRONMENT PARAMETERS"
        Parameters:
          - EnvironmentType
          - EnvironmentName
      - 
        Label:
          default: "NETWORK PARAMETERS"
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - DBPrivateSubnet1CIDR
          - DBPrivateSubnet2CIDR
          - CreateTransitGateway
          - OtherTransitGatewayID
      -
        Label: 
          default: "ROUTE53 PARAMETERS"
        Parameters:
          - CreatePrivateDomain
          - OtherHostedZoneIdRoute53
      -
        Label: 
          default: "ALB PARAMETERS"
        Parameters:
          - CreateALBCertificate
          - OtherARNCertificate
      -
        Label: 
          default: "AURORA DB PARAMETERS"
        Parameters:
          - CreateNewAuroraDB
          - DBSnapshotARN
          - DBUser
          - DBPassword
      -
        Label: 
          default: "ECS PARAMETERS"
        Parameters:
          - DesiredCount
          - ImageUrlApp1
          - ImageUrlApp2


# Nested Stacks
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-VPC.yml
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        DBPrivateSubnet1CIDR: !Ref DBPrivateSubnet1CIDR
        DBPrivateSubnet2CIDR: !Ref DBPrivateSubnet2CIDR
        CreateTransitGateway: !Ref CreateTransitGateway
        OtherTransitGatewayID: !Ref OtherTransitGatewayID

  NACLStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-NACL.yml
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBPrivateSubnet1: !GetAtt VPCStack.Outputs.DBPrivateSubnet1
        DBPrivateSubnet2: !GetAtt VPCStack.Outputs.DBPrivateSubnet2

  SGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NACLStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-SG.yml
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        VpcCIDR: !Ref VpcCIDR

  VPCEndpointStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SGStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-VPCEndpoints.yml
      TimeoutInMinutes: 30
      Parameters:
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        VPCEnpointSecurityGroup: !GetAtt SGStack.Outputs.VPCEnpointSecurityGroup
        PrivateRouteTable: !GetAtt VPCStack.Outputs.PrivateRouteTable

  EFSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SGStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-EFS.yml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        EFSSecurityGroup: !GetAtt SGStack.Outputs.EFSSecurityGroup

  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SGStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-ALB.yml
      TimeoutInMinutes: 10
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        PrivateDomainName: !Ref PrivateDomainName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ALBSecurityGroup: !GetAtt SGStack.Outputs.ALBSecurityGroup
        CreateALBCertificate: !Ref CreateALBCertificate
        OtherARNCertificate: !Ref OtherARNCertificate

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SGStack
      - VPCEndpointStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-RDS-Aurora.yml
      TimeoutInMinutes: 120
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        DBPrivateSubnet1: !GetAtt VPCStack.Outputs.DBPrivateSubnet1
        DBPrivateSubnet2: !GetAtt VPCStack.Outputs.DBPrivateSubnet2
        DBSecurityGroup: !GetAtt SGStack.Outputs.DBSecurityGroup
        DBType: !FindInMap [Aurora, InstanceTypes, !Ref EnvironmentType]
        CreateNewAuroraDB: !Ref CreateNewAuroraDB
        DBSnapshotARN: !Ref DBSnapshotARN

  Route53Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - ALBStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-Route53.yml
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        PrivateDomainName: !Ref PrivateDomainName
        VpcID: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        Route53SecurityGroup: !GetAtt SGStack.Outputs.Route53SecurityGroup
        AlbCanonicalHostedZoneID: !GetAtt ALBStack.Outputs.AlbCanonicalHostedZoneID
        AlbDNSName: !GetAtt ALBStack.Outputs.AlbDNSName
        RDSEnpointAddr: !GetAtt RDSStack.Outputs.RDSEnpointAddr
        RDSReaderEnpointAddr: !GetAtt RDSStack.Outputs.RDSReaderEnpointAddr
        CreatePrivateDomain: !Ref CreatePrivateDomain
        OtherHostedZoneIdRoute53: !Ref OtherHostedZoneIdRoute53

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SGStack
      - EFSStack
      - ALBStack
      - MQStack
      - RDSStack
    Properties:
      TemplateURL: !Sub https://kloudpepper-${EnvironmentName}-cf.s3.${AWS::URLSuffix}/kloudpepper-ECS-Fargate.yml
      TimeoutInMinutes: 30
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        EnvironmentName: !Ref EnvironmentName
        PrivateDomainName: !Ref PrivateDomainName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ECSSecurityGroup: !GetAtt SGStack.Outputs.ECSSecurityGroup
        DesiredCount: !Ref DesiredCount
        ImageUrlApp1: !Ref ImageUrlApp1
        ImageUrlApp2: !Ref ImageUrlApp2
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        RDSEnpointPort: !GetAtt RDSStack.Outputs.RDSEnpointPort
        TargetGroupAPP1: !GetAtt ALBStack.Outputs.TargetGroupAPP1
        TargetGroupAPP2: !GetAtt ALBStack.Outputs.TargetGroupAPP2
        FileSystemId: !GetAtt EFSStack.Outputs.FileSystemId
        AccessPointIdDataApp1: !GetAtt EFSStack.Outputs.AccessPointIdDataApp1
        AccessPointIdDataApp2: !GetAtt EFSStack.Outputs.AccessPointIdDataApp2