AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create a network ACL"

Parameters:
  EnvironmentType:
    Type: String

  EnvironmentName:
    Type: String

  VpcID:
    Type: String

  VpcCIDR:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  PrivateSubnet3:
    Type: String

  DBPrivateSubnet1:
    Type: String

  DBPrivateSubnet2:
    Type: String

  DBPrivateSubnet3:
    Type: String


Conditions:
  isProdEnvironmentType: !Equals [!Ref EnvironmentType, prod]


Resources:
### APP ###
# Specifies a network ACL for your private subnets
  PrivateNetworkACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VpcID
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateNetwork-ACL

# Acl association to private subnet 1
  PrivateSubnet1NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn: PrivateNetworkACL
    Properties:
      SubnetId: !Ref PrivateSubnet1
      NetworkAclId: !Ref PrivateNetworkACL

# Acl association to private subnet 2
  PrivateSubnet2NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn: PrivateNetworkACL
    Properties:
      SubnetId: !Ref PrivateSubnet2
      NetworkAclId: !Ref PrivateNetworkACL

# Acl association to private subnet 3
  PrivateSubnet3NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Condition: isProdEnvironmentType
    DependsOn: PrivateNetworkACL
    Properties:
      SubnetId: !Ref PrivateSubnet3
      NetworkAclId: !Ref PrivateNetworkACL

### DB ###
# Specifies a network ACL for your DB private subnets
  DBPrivateNetworkACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VpcID
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-DBPrivateNetwork-ACL

# Acl association to DB private subnet 1
  DBPrivateSubnet1NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn: DBPrivateNetworkACL
    Properties:
      SubnetId: !Ref DBPrivateSubnet1
      NetworkAclId: !Ref DBPrivateNetworkACL

# Acl association to DB private subnet 2
  DBPrivateSubnet2NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    DependsOn: DBPrivateNetworkACL
    Properties:
      SubnetId: !Ref DBPrivateSubnet2
      NetworkAclId: !Ref DBPrivateNetworkACL

# Acl association to DB private subnet 3
  DBPrivateSubnet3NetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Condition: isProdEnvironmentType
    DependsOn: DBPrivateNetworkACL
    Properties:
      SubnetId: !Ref DBPrivateSubnet3
      NetworkAclId: !Ref DBPrivateNetworkACL

### IN ###
# Private subnet inbound rules
  InboundOnpremiseNACLtoALB:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: "10.0.0.0/16" # from On-premise to ALB
      PortRange:
        From: '8445'
        To: '8445'

  InboundOnpremiseNACLtoR53Resolver:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '101'
      Protocol: "17"
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: "10.0.0.0/16" # from On-premise to Route53 Resolver
      PortRange:
        From: '53'
        To: '53'

  InboundVPCNACL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '102'
      Protocol: "-1" # ALL
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: !Ref VpcCIDR # VPC only

# DB Private subnet inbound rules
  InboundDBNACL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DBPrivateNetworkACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: "allow"
      Egress: "false"
      CidrBlock: !Ref VpcCIDR # VPC only
      PortRange:
        From: '33066'
        To: '33066'

### OUT ###
# Private subnet outbound rules
  OutboundOnpremiseNACLfromALB:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: "10.0.0.0/16" # from ALB to On-premise
      PortRange:
        From: '1024'
        To: '65535'

  OutboundOnpremiseNACLfromR53Resolver:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '101'
      Protocol: "17"
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: "10.0.0.0/16" # from Route53 Resolver to On-premise
      PortRange:
        From: '1024'
        To: '65535'

  OutboundVPCNACLTCP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PrivateNetworkACL
      RuleNumber: '102'
      Protocol: "-1"
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: !Ref VpcCIDR # VPC only

# DB Private subnet outbound rules
  OutboundDBNACL:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DBPrivateNetworkACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: "allow"
      Egress: "true"
      CidrBlock: !Ref VpcCIDR # VPC only
      PortRange:
        From: '1024'
        To: '65535'